/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard, Andrew Yang, Matthew Jasper, Adam McKenna
-/
module

public import FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Concrete.BadPrime

/-!
# The concrete Hecke algebra

Defines `HeckeAlgebra F D r S R`, the sub-`R`-algebra of the weight-2 form endomorphisms
generated by the Hecke operators `T_v` (for `v ∉ S`) and `U_{v,α}` (for `v ∈ S`),
and equips it with `CommRing`, `Ring`, and `Algebra R` instances via the cross-prime
commutation lemmas proved in `Concrete.BadPrime`.
-/

@[expose] public section

open NumberField IsQuaternionAlgebra.NumberField IsDedekindDomain

variable (F : Type*) [Field F] [NumberField F] [IsTotallyReal F]
variable (D : Type*) [Ring D] [Algebra F D] [IsQuaternionAlgebra F D]
variable (r : Rigidification F D)
variable (S : Finset (HeightOneSpectrum (𝓞 F)))
variable (R : Type*) [CommRing R]

open TotallyDefiniteQuaternionAlgebra

namespace TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm

open IsDedekindDomain.HeightOneSpectrum

open FiniteAdeleRing.GL2.Internal

open scoped TensorProduct

open HeckeOperator

/-- `HeckeAlgebra F D r S R` is the Hecke algebra associated to the weight 2
`R`-valued automorphic forms associated to the discriminant 1 totally definite
quaternion algebra `D` over the totally real field `F`, of level `U₁(S)` where `S` is
a finite set of nonzero primes `v` of `𝓞 F`. To make sense of this definition we choose
a rigidification `r`, that is, a fixed `𝔸_F^∞`-linear
isomorphism `D ⊗[F] 𝔸_F^∞ = M₂(𝔸_F^∞)`, enabling us to define level structures and
Hecke operators `Tᵥ` and `Uᵥ` using 2x2 matrices.

Details: `U₁(S)` is the subgroup of `(D ⊗[F] 𝔸_F^∞)ˣ` associated, via `r`, to the
matrices which are in `GL₂(𝓞ᵥ)` for all `v ∉ S` and which are of the form
`(a *; 0 a)` mod `v` for all `v ∈ S`. The Hecke algebra is defined to be the
sub-`R`-algebra of the weight 2 forms of level `U₁(S)` generated by the following
two kinds of Hecke operators: first there are the operators
`Tᵥ` associated to the matrices `(ϖᵥ 0; 0 1)` for `v ∉ S` (here `ϖᵥ ∈ 𝔸_F^∞` is a local
uniformiser supported at `v`). Second, there are the Hecke operators `Uᵥ,ₐ`
for `v ∈ S` and `0 ≠ αᵥ ∈ 𝓞ᵥ`, associated the matries `(αᵥ 0; 0 1)`.
These slightly nonstandard Hecke operators satisfy `Uᵥ,ₛ * Uᵥ,ₜ = Uᵥ,ₛₜ`
and in particular this Hecke algebra is commutative (Hecke operators supported
at distinct primes commute because the decomposition of the double cosets
into single cosets can be done purely locally).
-/
def HeckeAlgebra : Type _ :=
  (Algebra.adjoin R ({T r R v | v ∉ S} ∪
  {φ | ∃ (v : HeightOneSpectrum (𝓞 F)) (_hv : v ∈ S)
         (α : v.adicCompletionIntegers F) (hα : α ≠ 0), φ = U r S R α hα}) :
    Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

namespace HeckeAlgebra

noncomputable instance instRing :
    Ring (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Ring (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

noncomputable instance instAlgebra :
    Algebra R (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Algebra R (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

open scoped IsMulCommutative in
noncomputable instance instCommRing :
    CommRing (HeckeAlgebra F D r S R) := by
  haveI : IsMulCommutative (HeckeAlgebra F D r S R) := by
    simpa [HeckeAlgebra] using
      (Algebra.isMulCommutative_adjoin (R := R)
        (A := WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
          WeightTwoAutomorphicFormOfLevel (U1 r S) R)
        (s := {T r R v | v ∉ S} ∪
          {φ | ∃ (v : HeightOneSpectrum (𝓞 F)) (_hv : v ∈ S)
            (α : v.adicCompletionIntegers F) (hα : α ≠ 0), φ = U r S R α hα})
        (by
          intro x hx y hy
          rcases hx with hx | hx
          · rcases hy with hy | hy
            · rcases hx with ⟨v, hv, rfl⟩
              rcases hy with ⟨w, hw, rfl⟩
              by_cases hvw : v = w
              · subst hvw
                rfl
              · exact Internal.T_comm_of_ne (F := F) (D := D) (r := r) (S := S) (R := R)
                  (v := v) (w := w) hv hw hvw
            · rcases hx with ⟨v, hv, rfl⟩
              rcases hy with ⟨w, hw, β, hβ, rfl⟩
              exact Internal.T_comm_U_of_ne (F := F) (D := D) (r := r) (S := S) (R := R)
                (v := v) (w := w) hv hw
                (hvw := by
                  intro h
                  exact hv (h ▸ hw))
                (β := β) (hβ := hβ)
          · rcases hx with ⟨v, hv, α, hα, rfl⟩
            rcases hy with hy | hy
            · rcases hy with ⟨w, hw, rfl⟩
              exact (Internal.T_comm_U_of_ne (F := F) (D := D) (r := r) (S := S) (R := R)
                (v := w) (w := v) hw hv
                (hvw := by
                  intro h
                  exact hw (h ▸ hv))
                (β := α) (hβ := hα)).symm
            · rcases hy with ⟨w, hw, β, hβ, rfl⟩
              by_cases hvw : v = w
              · subst hvw
                exact Internal.U_comm (F := F) (D := D) (r := r) (S := S) (R := R) (v := v)
                  (hv := hv) (α := α) (hα := hα) (β := β) (hβ := hβ)
              · exact Internal.U_comm_of_ne (F := F) (D := D) (r := r) (S := S) (R := R)
                  (v := v) (w := w) hv hw hvw (α := α) (hα := hα) (β := β) (hβ := hβ)))
  exact inferInstance

variable {F S} in
/-- The Hecke operator Tᵥ as an element of the Hecke algebra. -/
noncomputable def T (v : HeightOneSpectrum (𝓞 F)) (hv : v ∉ S) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.T r R v, by
    apply Algebra.subset_adjoin
    left
    use v⟩

variable {F S} in
/-- The Hecke operator Uᵥ,ₐ as an element of the Hecke algebra. -/
noncomputable def U (v : HeightOneSpectrum (𝓞 F)) (hv : v ∈ S) (α : v.adicCompletionIntegers F)
    (hα : α ≠ 0) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.U r S R α hα, by
    apply Algebra.subset_adjoin
    right
    use v, hv, α, hα⟩

end HeckeAlgebra

end TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm
